#pragma once

// GENERATED by scripts/gen_defect_table.py, do not edit.
// Game version 1.1.21239. Ids with `tag birth_defect` per data/mutations/<group>.gon, plus -2 (missing part).
// Arms and legs both use the `legs` group.

#include <cstdint>
#include <span>
#include <string_view>

struct DefectGroup {
    std::string_view group;
    std::span<const int32_t> ids;
};

inline constexpr int32_t DEFECT_IDS_body[] = {-2, 700, 701, 702, 703, 704};
inline constexpr int32_t DEFECT_IDS_ears[] = {-2, 700, 701, 702, 703, 704};
inline constexpr int32_t DEFECT_IDS_eyebrows[] = {-2, 700, 701, 702};
inline constexpr int32_t DEFECT_IDS_eyes[] = {-2, 700, 701, 704, 705, 706};
inline constexpr int32_t DEFECT_IDS_head[] = {-2, 700, 701, 702, 703, 704, 705, 706};
inline constexpr int32_t DEFECT_IDS_legs[] = {-2, 700, 701, 702, 703, 704, 705, 706, 707};
inline constexpr int32_t DEFECT_IDS_mouth[] = {-2, 700, 701, 703, 704};
inline constexpr int32_t DEFECT_IDS_tail[] = {-2, 700, 701, 703, 704};
inline constexpr int32_t DEFECT_IDS_texture[] = {-2, 700, 701, 702, 703, 704, 705, 706};

inline constexpr DefectGroup DEFECT_GROUPS[] = {
    {"body", DEFECT_IDS_body},
    {"ears", DEFECT_IDS_ears},
    {"eyebrows", DEFECT_IDS_eyebrows},
    {"eyes", DEFECT_IDS_eyes},
    {"head", DEFECT_IDS_head},
    {"legs", DEFECT_IDS_legs},
    {"mouth", DEFECT_IDS_mouth},
    {"tail", DEFECT_IDS_tail},
    {"texture", DEFECT_IDS_texture},
};
