"""Generate src/clean_breeding/defect_table.hpp from data/mutations/*.gon in the game's resources.gpak.

For every mutation group (file name = group), lists the ids whose node has `tag birth_defect`, plus -2
(missing part, always a defect). Run again after a game update.

    python scripts/gen_defect_table.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import gpak

GAME_VERSION = "1.1.21239"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "clean_breeding", "defect_table.hpp")


def defect_ids(text):
    """ids (depth-1 nodes) of a group file whose body has a `tag ... birth_defect` line."""
    ids, depth, cur = set(), 0, None
    for raw in text.splitlines():
        line = raw.split("//", 1)[0].strip()
        if not line:
            continue
        m = re.match(r"^(-?\d+)\s*\{", line)
        if depth == 1 and m:
            cur = int(m.group(1))
        elif depth == 2 and cur is not None and re.match(r"^tag\b", line) and "birth_defect" in line.split():
            ids.add(cur)
        depth += line.count("{") - line.count("}")
    return ids


def main():
    index = gpak.read_index()
    groups = {}
    for name in sorted(index):
        m = re.fullmatch(r"data/mutations/(\w+)\.gon", name)
        if m:
            ids = defect_ids(gpak.read_file(name, index).decode("utf-8", "replace"))
            groups[m.group(1)] = sorted(ids | {-2})

    assert {700, 701, 704, 705, 706, -2} <= set(groups["eyes"]), groups["eyes"]
    assert set(range(700, 708)) <= set(groups["legs"]), groups["legs"]
    assert 704 in groups["head"], groups["head"]
    assert 1500 not in groups["mouth"]  # rat mouth: tag animal, not a defect (re_notes S3)

    lines = [
        "#pragma once",
        "",
        "// GENERATED by scripts/gen_defect_table.py, do not edit.",
        f"// Game version {GAME_VERSION}. Ids with `tag birth_defect` per data/mutations/<group>.gon, plus -2 (missing part).",
        "// Arms and legs both use the `legs` group.",
        "",
        "#include <cstdint>",
        "#include <span>",
        "#include <string_view>",
        "",
        "struct DefectGroup {",
        "    std::string_view group;",
        "    std::span<const int32_t> ids;",
        "};",
        "",
    ]
    for g, ids in groups.items():
        lines.append(f"inline constexpr int32_t DEFECT_IDS_{g}[] = {{{', '.join(map(str, ids))}}};")
    lines += ["", "inline constexpr DefectGroup DEFECT_GROUPS[] = {"]
    lines += [f'    {{"{g}", DEFECT_IDS_{g}}},' for g in groups]
    lines += ["};", ""]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    for g, ids in groups.items():
        print(g, ids)


main()
